name: Rebuild

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    outputs:
      node-version: 16
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Rebuild
        run: |
          sudo apt update
          sudo apt install build-essential libssl-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev

          cd /usr/src
          sudo wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
          sudo tar xzf Python-2.7.18.tgz
          cd Python-2.7.18
          sudo ./configure --enable-optimizations
          sudo make altinstall
          python2.7 --version

      - name: Upload built-dist
        uses: actions/upload-artifact@v4
        with:
          name: built-dist
          path: dist/

      - name: Upload built-media
        uses: actions/upload-artifact@v4
        with:
          name: built-media
          path: media/

  commit-to-develop-builds:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop-builds branch
        uses: actions/checkout@v3
        with:
          ref: develop-builds
          fetch-depth: 0

      - name: Clear out old builds
        run: |
          rm -rf dist/*
          rm -rf media/*

      - name: Download built-dist
        uses: actions/download-artifact@v5
        with:
          name: built-dist
          path: dist/

      - name: Download built-media
        uses: actions/download-artifact@v5
        with:
          name: built-media
          path: media/

      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: "Build"
          committer_name: GitHub Actions
          committer_email: actions@github.com
